// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;

namespace Pulumi.Random
{
    internal class ResourcePackage : IResourcePackage
    {
        public string Name => "random";

        public string? Version => Utilities.Version;

        [Obsolete("The overload with 4 parameters is deprecated and will be removed")]
        public ProviderResource ConstructProvider(string name, string type, System.Collections.Generic.IDictionary<string, object?>? args, string urn)
            => ConstructProvider(name, type, urn);

        public ProviderResource ConstructProvider(string name, string type, string urn)
        {
            if (type == "pulumi:providers:random")
                return new Provider(name, default!, new CustomResourceOptions {Urn=urn});
            throw new Exception($"Unknown provider type {type}");
        }

        public Resource Construct(string name, string type, string urn)
        {
            var options = new CustomResourceOptions {Urn=urn};
            switch (type)
            {
                case "random:index/randomId:RandomId":
                    return new Pulumi.Random.RandomId(name, default!, options);
                case "random:index/randomInteger:RandomInteger":
                    return new Pulumi.Random.RandomInteger(name, default!, options);
                case "random:index/randomPassword:RandomPassword":
                    return new Pulumi.Random.RandomPassword(name, default!, options);
                case "random:index/randomPet:RandomPet":
                    return new Pulumi.Random.RandomPet(name, default!, options);
                case "random:index/randomShuffle:RandomShuffle":
                    return new Pulumi.Random.RandomShuffle(name, default!, options);
                case "random:index/randomString:RandomString":
                    return new Pulumi.Random.RandomString(name, default!, options);
                case "random:index/randomUuid:RandomUuid":
                    return new Pulumi.Random.RandomUuid(name, default!, options);
            }
            throw new Exception($"Unknown resource type {type}");
        }
    }
}
